const practices = [
  {
    "Id": "1",
    "Name": "Vensa Health Clinic",
    "Address": "459 Great South Road, Penrose, Auckland, Auckland 1061, New Zealand",
    "Phone": null,
    "IsOnline": true,
    "PictureUrl": "http://placekitten.com/300/200",
    "IsUsingVensa": true,
    "PracticeId": "1",
    "UrlName": "vensahealth",
  },
  {
    "Id": "2",
    "Name": "Knicks Knee Club",
    "Address": "459 Great South Road, Penrose, Auckland, Auckland 1061, New Zealand",
    "Phone": null,
    "IsOnline": true,
    "PictureUrl": "http://www.newhealthadvisor.com/images/1HT02822/1.jpg",
    "PracticeId": "2",
    "UrlName": "knicksknees",
    "IsUsingVensa": true,
  },
  {
    "Id": "3",
    "Name": "Dr Hu's Tardis",
    "Address": "459 Great South Road, Penrose, Auckland, Auckland 1061, New Zealand",
    "Phone": null,
    "IsOnline": false,
    "PictureUrl": "http://tardistopia.net/wp-content/uploads/2013/06/dr-n-sonic-screwdriver-david-tennant-527197_800_533.jpg",
    "IsUsingVensa": false,
    "PracticeId": "3",
    "UrlName": "drhus",
  },
  {
    "Id": "4",
    "Name": "Real House Wives Of Auckland Medical Center",
    "Address": "459 Great South Road, Penrose, Auckland, Auckland 1061, New Zealand",
    "Phone": "027 485 9550",
    "IsOnline": true,
    "PictureUrl": "http://www.stuff.co.nz/content/dam/images/1/d/f/q/1/r/image.related.StuffLandscapeSixteenByNine.620x349.1dfq72.png/1470802050819.jpg",
    "IsUsingVensa": true,
    "PracticeId": "4",
    "UrlName": "realhousewives",
  },
  {
    "Id": "5",
    "Name": "Shane Bond's Sports Injuries",
    "Address": "459 Great South Road, Penrose, Auckland, Auckland 1061, New Zealand",
    "Phone": null,
    "IsOnline": true,
    "PictureUrl": "http://placekitten.com/300/200",
    "IsUsingVensa": true,
    "PracticeId": "5",
    "UrlName": "shanebondssportsinjuries",
  },
  {
    "Id": "6",
    "Name": "Chris Martin's Batting School",
    "Address": "459 Great South Road, Penrose, Auckland, Auckland 1061, New Zealand",
    "Phone": null,
    "IsOnline": true,
    "PictureUrl": "http://www.newhealthadvisor.com/images/1HT02822/1.jpg",
    "IsUsingVensa": true,
    "PracticeId": "6",
    "UrlName": "chris-martin-batting-school",
  },
  {
    "Id": "7",
    "Name": "Agueroooooooo Emergency Rescue",
    "Address": "459 Great South Road, Penrose, Auckland, Auckland 1061, New Zealand",
    "Phone": null,
    "IsOnline": false,
    "PictureUrl": "http://tardistopia.net/wp-content/uploads/2013/06/dr-n-sonic-screwdriver-david-tennant-527197_800_533.jpg",
    "IsUsingVensa": true,
    "PracticeId": "7",
    "UrlName": "aggies-emergency",
  },
  {
    "Id": "8",
    "Name": "Ronaldinho's Dentists",
    "Address": "459 Great South Road, Penrose, Auckland, Auckland 1061, New Zealand",
    "Phone": null,
    "IsOnline": true,
    "PictureUrl": "http://www.stuff.co.nz/content/dam/images/1/d/f/q/1/r/image.related.StuffLandscapeSixteenByNine.620x349.1dfq72.png/1470802050819.jpg",
    "IsUsingVensa": false,
    "PracticeId": "8",
    "UrlName": "dinos-dental",
  },
  {
    "Id": "9",
    "Name": "Mohammad Amir's \"Fixing\" Club",
    "Address": "459 Great South Road, Penrose, Auckland, Auckland 1061, New Zealand",
    "Phone": null,
    "IsOnline": false,
    "PictureUrl": "http://tardistopia.net/wp-content/uploads/2013/06/dr-n-sonic-screwdriver-david-tennant-527197_800_533.jpg",
    "IsUsingVensa": false,
    "PracticeId": "9",
    "UrlName": "fix-it-now",
  },
  {
    "Id": "10",
    "Name": "Mike Tyson's ENT Specialists",
    "Address": "459 Great South Road, Penrose, Auckland, Auckland 1061, New Zealand",
    "Phone": null,
    "IsOnline": true,
    "PictureUrl": "http://www.stuff.co.nz/content/dam/images/1/d/f/q/1/r/image.related.StuffLandscapeSixteenByNine.620x349.1dfq72.png/1470802050819.jpg",
    "IsUsingVensa": true,
    "PracticeId": "10",
    "UrlName": "ima-eat-your-ear",
  },
];

export default practices;
